# Generated by Django 4.1.3 on 2022-11-18 03:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionWithProvider',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, verbose_name='Id')),
                ('pay_id', models.IntegerField(verbose_name='Pay ID of institution')),
                ('provider', models.CharField(max_length=100, verbose_name='Provider')),
                ('concept', models.TextField(verbose_name='Concept')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount')),
                ('_status', models.CharField(choices=[('S', 'Successful'), ('F', 'Failed'), ('C', 'Cancelled'), ('P', 'In process')], default='P', max_length=1, verbose_name='Status')),
                ('_createdDate', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Creation date')),
            ],
            options={
                'verbose_name': 'Connection with provider',
                'verbose_name_plural': 'Connections with providers',
            },
        ),
        migrations.CreateModel(
            name='Phase1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('payment_method', models.CharField(choices=[('DC', 'Debit card'), ('CC', 'Credit card')], max_length=2, verbose_name='Payment method')),
                ('connection_with_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.connectionwithprovider', verbose_name='Connection with provider')),
            ],
            options={
                'verbose_name': 'Phase 1',
                'verbose_name_plural': 'Phases 1',
            },
        ),
        migrations.CreateModel(
            name='Phase2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(choices=[('EB', 'East Bank'), ('WB', 'Western Bank')], max_length=2, verbose_name='Bank')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('lastname', models.CharField(max_length=50, verbose_name='Last name')),
                ('number_id', models.CharField(max_length=10, verbose_name='Number id')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone number')),
                ('phase1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.phase1', verbose_name='Phase 1')),
            ],
            options={
                'verbose_name': 'Phase 2',
                'verbose_name_plural': 'Phases 2',
            },
        ),
    ]
