# Generated by Django 4.1.3 on 2022-11-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionwithprovider',
            name='id',
            field=models.TextField(blank=True, primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
