# Generated by Django 4.1.3 on 2022-11-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionwithprovider',
            name='receipt',
            field=models.CharField(blank=True, max_length=20, verbose_name='Receipt number'),
        ),
    ]
