# Generated by Django 4.1.3 on 2022-11-14 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=16, unique=True, verbose_name='Number')),
                ('_isActive', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Is active')),
                ('_creationDate', models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Creation date')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.bank', verbose_name='Bank')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='banks.card')),
                ('securityNumber', models.CharField(editable=False, max_length=3, null=True, verbose_name='Security number')),
                ('quota', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Quota')),
                ('type', models.CharField(choices=[('VS', 'Visa'), ('MC', 'Mastercard'), ('AE', 'Ametican Express')], editable=False, max_length=2, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Credit card',
                'verbose_name_plural': 'Credit cards',
            },
            bases=('banks.card',),
        ),
        migrations.CreateModel(
            name='DebitCard',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='banks.card')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Balance')),
            ],
            options={
                'verbose_name': 'Debit card',
                'verbose_name_plural': 'Debit cards',
            },
            bases=('banks.card',),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passarellaID', models.TextField(verbose_name='Passarella')),
                ('institution', models.CharField(max_length=100, verbose_name='Insititution')),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=9, verbose_name='Amount')),
                ('concept', models.TextField(blank=True, verbose_name='Concept')),
                ('_status', models.CharField(choices=[('S', 'Successful'), ('F', 'Failed'), ('P', 'In process')], default='P', max_length=1, verbose_name='Status')),
                ('_createdDate', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Creation date')),
                ('_finishedDate', models.DateTimeField(null=True, verbose_name='Finish date')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banks.card', verbose_name='Card')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('_status', models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True, verbose_name='Status')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.bank', verbose_name='Bank')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('lastName', models.CharField(max_length=50, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('idNumber', models.CharField(max_length=10, unique=True, verbose_name='Identification number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='HistoricalTransaction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('passarellaID', models.TextField(verbose_name='Passarella')),
                ('institution', models.CharField(max_length=100, verbose_name='Insititution')),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=9, verbose_name='Amount')),
                ('concept', models.TextField(blank=True, verbose_name='Concept')),
                ('_status', models.CharField(choices=[('S', 'Successful'), ('F', 'Failed'), ('P', 'In process')], default='P', max_length=1, verbose_name='Status')),
                ('_createdDate', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Creation date')),
                ('_finishedDate', models.DateTimeField(null=True, verbose_name='Finish date')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('card', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='banks.card', verbose_name='Card')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Transaction',
                'verbose_name_plural': 'historical Transactions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='card',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.person', verbose_name='Person'),
        ),
    ]
