# Generated by Django 4.1.3 on 2022-11-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Amount'),
        ),
    ]
