# Generated by Django 4.1.3 on 2022-11-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltransaction',
            name='number_bill',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Number bill'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='number_bill',
            field=models.CharField(blank=True, max_length=20, primary_key=True, serialize=False, verbose_name='Number bill'),
        ),
    ]
