# Generated by Django 4.1.3 on 2022-11-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_alter_historicaltransaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(choices=[('EB', 'East Bank'), ('WB', 'Western Bank')], max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicaltransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('C', 'Consult'), ('P', 'Pay')], max_length=1, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount'),
        ),
    ]
