# Generated by Django 4.1.3 on 2022-11-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_alter_bank_name_alter_historicaltransaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('C', 'Consult'), ('P', 'Pay')], max_length=1, verbose_name='Name'),
        ),
    ]
