# Generated by Django 4.1.3 on 2022-11-12 17:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_expiration', models.DateTimeField(editable=False, verbose_name='Expiration date')),
                ('_generatedDate', models.DateTimeField(default=datetime.datetime(2022, 11, 12, 12, 17, 11, 468245), editable=False, verbose_name='Creation date')),
                ('_paid', models.BooleanField(choices=[(True, 'Paid'), (False, 'Unpaid')], default=False, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('city', models.CharField(choices=[('BAQ', 'Barranquilla'), ('CTG', 'Cartagena'), ('SMR', 'Santa Marta'), ('SIN', 'Sincelejo'), ('MON', 'Monteria')], default='BAQ', max_length=3, verbose_name='City')),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campus',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPay',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('_date', models.DateTimeField(default=datetime.datetime(2022, 11, 12, 12, 17, 11, 469244), editable=False, verbose_name='Creation date')),
                ('_status', models.CharField(choices=[('S', 'Started'), ('F', 'Finished'), ('P', 'In process'), ('C', 'cancelled')], default='P', max_length=1, verbose_name='Status')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Pay',
                'verbose_name_plural': 'historical Pays',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
            },
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_date', models.DateTimeField(default=datetime.datetime(2022, 11, 12, 12, 17, 11, 469244), editable=False, verbose_name='Creation date')),
                ('_status', models.CharField(choices=[('S', 'Started'), ('F', 'Finished'), ('P', 'In process'), ('C', 'cancelled')], default='P', max_length=1, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Pay',
                'verbose_name_plural': 'Pays',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022, verbose_name='Year')),
                ('period', models.CharField(choices=[('10', '10'), ('20', '20'), ('30', '30')], max_length=2, verbose_name='Period')),
                ('value', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('type', models.CharField(choices=[('PR', 'Pregrado'), ('PS', 'Posgrado')], max_length=2, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, max_length=10, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('lastName', models.CharField(max_length=255, verbose_name='Last name')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.campus', verbose_name='Campus')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
