# Generated by Django 4.1.3 on 2022-11-14 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Student', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='service',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.campus', verbose_name='Campus'),
        ),
        migrations.AddField(
            model_name='semester',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.program', verbose_name='Program'),
        ),
        migrations.AddField(
            model_name='program',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='pay',
            name='bills',
            field=models.ManyToManyField(related_name='Pay', to='institutions.bill'),
        ),
        migrations.AddField(
            model_name='pay',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.student', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='historicalpay',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalpay',
            name='student',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='institutions.student', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='campus',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution', verbose_name='Institution'),
        ),
        migrations.AddField(
            model_name='bill',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.semester', verbose_name='Semester'),
        ),
        migrations.AddField(
            model_name='bill',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.student', verbose_name='Student'),
        ),
    ]
