# Generated by Django 4.1.3 on 2022-11-06 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='_generatedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 18, 13, 0, 348291), editable=False, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='historicalpay',
            name='_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 18, 13, 0, 349286), editable=False, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 6, 18, 13, 0, 349286), editable=False, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=10, verbose_name='Code'),
        ),
    ]
