# Generated by Django 4.1.3 on 2022-11-07 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0007_alter_bill__generateddate_alter_historicalpay__date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpay',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='pay',
            name='bill',
        ),
        migrations.AddField(
            model_name='historicalpay',
            name='_status',
            field=models.CharField(choices=[('S', 'Started'), ('F', 'Finished'), ('P', 'In process'), ('C', 'cancelled')], default='P', max_length=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='pay',
            name='_status',
            field=models.CharField(choices=[('S', 'Started'), ('F', 'Finished'), ('P', 'In process'), ('C', 'cancelled')], default='P', max_length=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='pay',
            name='bills',
            field=models.ManyToManyField(related_name='Pay', to='institutions.bill'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='_generatedDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 7, 10, 29, 30, 165182), editable=False, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='historicalpay',
            name='_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 7, 10, 29, 30, 165182), editable=False, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 7, 10, 29, 30, 165182), editable=False, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True, verbose_name='Code'),
        ),
    ]
