# Generated by Django 4.1.3 on 2022-11-06 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_finished', models.BooleanField(default=False, verbose_name='Is finished')),
                ('pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.pay', verbose_name='Institution oay')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.transaction', verbose_name='Bank transaction')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
            },
        ),
    ]
