# Generated by Django 4.1.3 on 2022-11-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_fase2_remove_shop_pay_delete_fase2pse_delete_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase2',
            name='concept',
            field=models.CharField(blank=True, max_length=500, verbose_name='Concept'),
        ),
        migrations.AlterField(
            model_name='fase2',
            name='institution',
            field=models.CharField(blank=True, max_length=100, verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='fase2',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, verbose_name='Value'),
        ),
    ]
