# Generated by Django 4.1.3 on 2022-11-05 22:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DC', 'Debit'), ('CC', 'Credit')], max_length=2, verbose_name='Type')),
                ('number', models.CharField(editable=False, max_length=16, unique=True, verbose_name='Number')),
                ('securityNumber', models.CharField(editable=False, max_length=3, null=True, verbose_name='Security number')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Balance')),
                ('_isActive', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Is active')),
                ('_creationDate', models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Creation date')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.bank', verbose_name='Bank')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('lastName', models.CharField(max_length=50, verbose_name='Last name')),
                ('idNumber', models.CharField(max_length=10, unique=True, verbose_name='Identification number')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=9, verbose_name='Amount')),
                ('concept', models.TextField(blank=True, verbose_name='Concept')),
                ('_status', models.CharField(choices=[('S', 'Successful'), ('F', 'Failed'), ('P', 'In process')], default='P', max_length=1, verbose_name='Status')),
                ('_DateTime', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date time')),
                ('card', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banks.card', verbose_name='Card')),
                ('person', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banks.person', verbose_name='Payer')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('_status', models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True, verbose_name='Status')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.bank', verbose_name='Bank')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.AddField(
            model_name='card',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.person', verbose_name='Person'),
        ),
    ]
